# comment
on:
  pull_request: {}
  push:
    branches: ["master", "main"]
  
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: da822fa583316cca9c0e344479ed55cb2968ad88b7204886c6b6b5b185507e7b
